### ISSUE TITLE
Possible successor to cold-widow

### ISSUE THREAD

**Issue by DonaldTsang** [mihaigiurgeanu/cold-widow#2]
Please take a look at TxQR, which uses fountain codes for its implementation
- https://github.com/divan/txqr
- https://github.com/divan/txqr-reader
- https://github.com/ThePlasmaRailgun/TXQR-Android

**Comment by mihaigiurgeanu** [comment]
I take a look at your project and it seems quite nice. I don't think it is a successor of cold-widow which is a more basic project written in haskell.
